# Generated by Django 3.2 on 2021-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_field',
            field=models.FileField(null=True, upload_to='user_uploads/'),
        ),
    ]
